# Site information
site_name: B-Zone SA:MP Rules

# Theme elements
theme:
  name: material
  favicon: images/favicon.png
  logo: https://res.b-zone.ro/ll/actual.jpg
  icon:
    alternate: material/format-letter-case
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Toggle dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Toggle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to auto mode

    # Auto theme
    - media: "(prefers-color-scheme)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

# Used plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ro
          default: true
          name: Română
          build: true
        - locale: en
          name: English
          build: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# Used extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Copyright elements and cookie settings
copyright: >
  Copyright &copy; 2008-<script>document.write(new Date().getFullYear())</script> B-ZONE All Rights Reserved

# Custom css
extra_css:
  - stylesheets/extra.css

# Footer elements
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.b-zone.ro
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@BZoneCommunity
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@bzonero
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bzonero
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences (like keeping your desired site theme).
    actions:
      - accept
      - reject

# Navigation
nav:
  - Server Rules:
    - Server Rules: index.md
  - Leader Rules:
    - Leader Rules: leaders/leader-rules.md
  - Faction Rules:
    - General Rules:
      - Peaceful Faction and Mixt General Rules: factions/peaceful-and-mixt-faction-rules.md
      - Gang General Rules: factions/gang-rules.md
      - Department General Rules: factions/department-rules.md
    - Internal Rules:
      - Peaceful Factions:
        - Paramedics Rules: factions/peaceful/paramedics.md
        - News Reporters Rules: factions/peaceful/news-reporters.md
        - Tow Truck Rules: factions/peaceful/ttc.md
        - Taxi Rules: factions/peaceful/taxi.md
        - School Instructors Rules: factions/peaceful/school-instructors.md
      - Gangs:
        - Green Street Bloods Rules: factions/gangs/gsb.md
        - Verdant Family Rules: factions/gangs/vdt.md
        - Vietnamese Boys Rules: factions/gangs/vtb.md
        - The Tsar Bratva Rules: factions/gangs/ttb.md
        - Red Dragon Triad Rules: factions/gangs/rdt.md
        - Southern Pimps Rules: factions/gangs/sp.md
        - Avispa Rifa Rules: factions/gangs/rifa.md
        - 69 Pier Mobs Rules: factions/gangs/69pm.md
        - El Loco Cartel Rules: factions/gangs/elc.md
      - Departments:
        - PD Rules: factions/departments/pd.md
        - FBI Rules: factions/departments/fbi.md
        - NG Rules: factions/departments/ng.md
      - Mixt Factions:
        - Hitmen Agency Rules: factions/mixt/hitmen.md
        - Sons Of Anarchy Rules: factions/mixt/soa.md
        - Mayor Rules: factions/mixt/mayor.md
  - SA:MP Wiki:
    - Wiki Info:
      - Vehicles:
        - Cash Vehicles: wiki-info/vehicles/cash-vehicles.md
        - Gold Vehicles: wiki-info/vehicles/gold-vehicles.md
        - Shop Vehicles: wiki-info/vehicles/shop-vehicles.md
        - Premium Vehicles: wiki-info/vehicles/premium-vehicles.md
        - How to Buy: wiki-info/vehicles/how-to-buy.md
        - Useful Commands: wiki-info/vehicles/useful-commands.md
      - House:
        - General Description: wiki-info/house/general-description.md
        - Useful Commands: wiki-info/house/useful-commands.md
      - Business:
        - General Description: wiki-info/business/general-description.md
        - Gas Stations: wiki-info/business/gas-stations.md
        - 24/7: wiki-info/business/24-7.md
        - Fast Food: wiki-info/business/fast-food.md
        - Clothing Stores: wiki-info/business/clothing-stores.md
        - Gun Shops: wiki-info/business/gun-shops.md
        - Clubs & Bars: wiki-info/business/clubs-bars.md
        - Restaurants: wiki-info/business/restaurants.md
        - Pay n Sprays: wiki-info/business/pay-n-sprays.md
        - Tuning: wiki-info/business/tuning.md
        - Arenas: wiki-info/business/arenas.md
        - CNN: wiki-info/business/cnn.md
        - Rent: wiki-info/business/rent.md
        - Melee Weapons Store: wiki-info/business/melee-weapons-store.md
        - Sex Shops: wiki-info/business/sex-shops.md
        - Poker Casino: wiki-info/business/poker-casino.md
        - Blackjack Casino: wiki-info/business/blackjack-casino.md
        - Car Insurance: wiki-info/business/car-insurance.md
        - PubG Arena: wiki-info/business/pubg-arena.md
        - Car Color: wiki-info/business/car-color.md
        - Other Business: wiki-info/business/other-business.md
        - Useful Commands: wiki-info/business/useful-commands.md
      - Factions:
        - General Description: wiki-info/factions/general-description.md
        - Activity Report: wiki-info/factions/activity-report.md
        - SF School Instructors: wiki-info/factions/sf-school-instructors.md
        - LS School Instructors: wiki-info/factions/ls-school-instructors.md
        - LV School Instructors: wiki-info/factions/lv-school-instructors.md
        - LV Taxi: wiki-info/factions/lv-taxi.md
        - LS Taxi: wiki-info/factions/ls-taxi.md
        - SF Taxi: wiki-info/factions/sf-taxi.md
        - News Reporters: wiki-info/factions/news-reporters.md
        - Tow Truck Company: wiki-info/factions/tow-truck-company.md
        - Mayor: wiki-info/factions/mayor.md
        - Paramedics: wiki-info/factions/paramedics.md
        - El Loco Cartel: wiki-info/factions/el-loco-cartel.md
        - Avispa Rifa: wiki-info/factions/avispa-rifa.md
        - Southern Pimps: wiki-info/factions/southern-pimps.md
        - 69 Pier Mobs: wiki-info/factions/69-pier-mobs.md
        - Verdant Family: wiki-info/factions/verdant-family.md
        - Green Street Bloods: wiki-info/factions/green-street-bloods.md
        - The Tsar Bratva: wiki-info/factions/the-tsar-bratva.md
        - FBI: wiki-info/factions/fbi.md
        - LVPD: wiki-info/factions/lvpd.md
        - SFPD: wiki-info/factions/sfpd.md
        - LSPD: wiki-info/factions/lspd.md
        - National Guard: wiki-info/factions/national-guard.md
        - Hitmen Agency: wiki-info/factions/hitmen-agency.md
        - Sons of Anarchy: wiki-info/factions/sons-of-anarchy.md
      - Jobs:
        - Pocket Thief: wiki-info/factions/sons-of-anarchy.md
      - Website:
        - My Account: wiki-info/factions/sons-of-anarchy.md
      - Other Systems:
        - Rob: wiki-info/factions/sons-of-anarchy.md
      - Useful Commands:
        - Account: wiki-info/factions/sons-of-anarchy.md
      - Shop:
        - Gold Vehicles: wiki-info/factions/sons-of-anarchy.md
      - Tutorials:
        - How to Install SA:MP: wiki-info/factions/sons-of-anarchy.md
        - Audio Plugin: wiki-info/factions/sons-of-anarchy.md
